//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundTrack.PrivatImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankImportDetails
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public Nullable<int> AppCode { get; set; }
        public string Card { get; set; }
        public string CardAmount { get; set; }
        public string Description { get; set; }
        public string Rest { get; set; }
        public string Terminal { get; set; }
        public System.DateTime Trandate { get; set; }
        public bool IsLooked { get; set; }
    }
}
