//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundTrack.PrivatImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgAccounts
    {
        public int Id { get; set; }
        public string AccountType { get; set; }
        public Nullable<int> BankAccId { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrentBalance { get; set; }
        public string Description { get; set; }
        public string OrgAccountName { get; set; }
        public int OrgId { get; set; }
        public Nullable<int> TargetId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
    }
}
